language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

#branches:
#  only:
#    - master

cache:
  directories:
    - node_modules

script:
  - npm i
  - npm start build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
#  on:
#    branch: master
