image: node:10-alpine

stages:
  - test
  - build
  - publish

test:
  stage: test

  cache:
    paths:
      - node_modules/

  before_script:
    - npm install

  script:
    - npm run test

  tags:
    - tests

build:
  stage: build

  before_script:
    - npm install

  script:
    - npm run prepare

  tags:
    - build

publish:
  stage: publish
  when: manual

  only:
    - tags

  before_script:
    - npm install

  script:
    - echo '//nexus.mobbtech.com/repository/npm-internal/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --unsafe-perm

  tags:
    - build